### ISSUE TITLE
Add ability to ignore global resets somehow?

### ISSUE THREAD

**Issue by wesbos** [astahmer/atomic-css-devtools#3]
Not sure how you'd do this, but common selectors for applying border-box to everything in Normalize.css or Tailwind Preflight add a bit a noise.

Would be nice to be able to just filter these out entirely from the Atomic CSS panel.

<img width="552" alt="Screenshot 2024-10-16 at 10 55 20 AM" src="https://github.com/user-attachments/assets/9f084dc0-3b6b-41ab-bddb-e8766008f985">

**Comment by wesbos** [comment]
Realizing the CSS Layers UI kind of fixes this for me - I can just collapse the base/reset CSS Layer. So feel free to close this!

**Comment by astahmer** [comment]
yes I noticed those too but was unsure on how to fix it / if a fix was needed

maybe we could specifically treat that selector `*, ::after, ::before` and hide it when a rule is applied due to that exact selector string

**Comment by wesbos** [comment]
Yeah, or at least match a few of the common ones:

tailwind: `*, ::after, ::before, ::backdrop, ::file-selector-button ` 

Common copy pasta `*, *:before, *:after {  box-sizing: inherit; }` 

panda: `*, ::backdrop, :after, :before {` 

Maybe anything with a top level `*`?

**Comment by astahmer** [comment]
done [here](https://github.com/astahmer/atomic-css-devtools/commit/83d9050d8fc3b70ed9eb2e98f013ce4ffc91da58), it was just released in 0.0.9

it will hide those styles by default, but you can show them if needed

![image](https://github.com/user-attachments/assets/c4b5cc79-29be-4713-b714-f8ef9f758e1a)
![image](https://github.com/user-attachments/assets/22539600-a334-4e65-a3da-d288075cd655)

**Comment by wesbos** [comment]
beautiful! Thank you
